
name: Deploy to App Engine

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    permissions:
      contents: 'read'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Deploy to App Engine
        id: deploy
        uses: 'google-github-actions/deploy-appengine@v0'
